print('Guilherme')
print ('Jordan')
print ('Nadal')
print ('Senna')
print ('Pelé')
print ('Spidersilva')
print ('Tom brady')
print ('APENAS OS GOATS')

print ("Meu nome é Guilherme, faço o curso de engenharia de software na UMC")